### ISSUE TITLE
Project doesn't build under freertos (202007.00) 

### ISSUE THREAD

**Issue by Ruan42** [tgsong/amazon-freertos-examples#5]
Running the project as is works, but after upgrading submodule 
**freertos : 4e8219e0923d459900924ff760ac492224b131fb freertos (202007.00)**
getting include errors 
"../src/main.c:44:30: fatal error: FreeRTOS_Sockets.h: No such file or directory"

**Comment by tgsong** [comment]
Thanks for reporting, in the latest release, espressif has switched to lwip by default, as a result the `main.cpp` file from their demo is updated. I just updated my  `src/main.cpp` file and it's working now, please try the latest master branch. Thanks!
